name: cw_core
description: "Technolab Circulaire Wandeling - Core"
version: 1.0.0+1

publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^10.0.0
