name: Build & Publish Backend Docker Image

on:
  workflow_call:

jobs:
  build-backend:
    name: Build & Publish Dart Frog Docker Image
    runs-on: ubuntu-latest

    permissions:
      packages: write
      id-token: write

    defaults:
      run:
        working-directory: apps/cw_api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image name
        id: vars
        run: |
          IMAGE="ghcr.io/${GITHUB_REPOSITORY,,}/api"
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t ${{ steps.vars.outputs.image }}:latest .

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ steps.vars.outputs.image }}:latest
